[package]
name = "blaze-db"
version = "0.1.0"
edition = "2024"
autobins = false

[lib]
name = "blaze_db"
path = "src/lib.rs"

[[bin]]
name = "blzdb"
path = "src/bin/client.rs"

[[bin]]
name = "blzsrv"
path = "src/bin/server.rs"

[[bin]]
name = "nsw"
path = "sandbox/nsw.rs"

[[bin]]
name = "hnsw"
path = "sandbox/hnsw.rs"

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[[example]]
name = "amazon_demo"
path = "examples/amazon_demo.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
incremental = false
debug = false

[profile.release.package."*"]
opt-level = 3
codegen-units = 1
strip = true
incremental = false
debug = false

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
memmap2 = "0.9.9"
rayon = "1.11.0"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
anyhow = "1.0.100"
colored = "3.1.1"
bincode = "2.0.1"
clap = { version = "4.5.54", features = ["derive"] }
axum = "0.8.8"
uuid = { version = "1.11.0", features = ["v4"] }
dirs = "6.0.0"
toml = "0.9.8"
chrono = "0.4.43"
wide = "1.1.1"
sha2 = "0.10.9"
csv = "1.4.0"
rand = "0.9.2"
indicatif = "0.18.3"
sysinfo = "0.37.2"
lazy_static = "1.5.0"
lru = "0.16.3"
# thiserror = "2.0.18"

[dev-dependencies]
criterion = "0.8.0"
tempfile = "3.8"
futures = "0.3"
