[package]
name = "blaze-db"
version = "0.1.0"
edition = "2024"
autobins = false

[lib]
name = "blaze_db"
path = "src/lib.rs"

[[bin]]
name = "blzdb"
path = "src/bin/client.rs"

[[bin]]
name = "blzsrv"
path = "src/bin/server.rs"

[[bin]]
name = "nsw"
path = "hnsw_scrape/nsw.rs"

[[bin]]
name = "hnsw"
path = "hnsw_scrape/hnsw.rs"

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = false
incremental = false
debug = false

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
memmap2 = "0.9.9"
rayon = "1.11.0"
reqwest = { version = "0.13.1", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.149"
anyhow = "1.0.100"
colored = "3.0.0"
bincode = "2.0.1"
clap = { version = "4.5.54", features = ["derive"] }
axum = "0.8.7"
uuid = { version = "1.11.0", features = ["v4"] }
dirs = "6.0.0"
toml = "0.9.8"
chrono = "0.4.42"
wide = "1.0.2"
sha2 = "0.10.9"
csv = "1.4.0"
rand = "0.9.2"
indicatif = "0.18.3"
sysinfo = "0.37.2"

[dev-dependencies]
criterion = "0.8.0"
tempfile = "3.8"